from textwrap import dedent

import pytest
from part_2 import solve


@pytest.mark.parametrize(
    argnames=("input_lines", "expected"),
    argvalues=[(1, 1), (3, 2), (5, 4), (7, 8), (9, 13), (11, 20), (17, 40)],
)
def test_solve(input_lines: int, expected: int) -> None:
    input_text = dedent("""\
        .......S.......
        ...............
        .......^.......
        ...............
        ......^.^......
        ...............
        .....^.^.^.....
        ...............
        ....^.^...^....
        ...............
        ...^.^...^.^...
        ...............
        ..^...^.....^..
        ...............
        .^.^.^.^.^...^.
        ...............
    """)

    input_text = "\n".join(input_text.split("\n")[:input_lines])
    assert solve(input_text) == expected
